name: "Sara's toolbox"
description: "Sharing is caring."
author: "dotsara"

# url: "http://localhost:4000"
#url: "http://dotsara.github.io"


exclude: [README.md, Rakefile, NOTES.md]
paginate: 16
permalink: /:year/:title
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-paginate