name: "Sara's toolbox"
description: "Sharing is caring."
author: "Sara Flemming, dotsara"

#url: "http://localhost:4000"
url: "http://dotsara.github.io"


exclude: [README.md, Rakefile, NOTES.md]
paginate: 16
permalink: /:year/:title
gems:
  - jemoji