name: "Toolbox"
description: "Stuff and things."
author: "dotsara"
avatar: https://avatars0.githubusercontent.com/u/339829?v=3&s=460

url: "http://localhost:4000"
# url: "http://dotsara.github.io"


exclude: [README.md, Rakefile]
paginate: 16
permalink: /:year/:title
gems:
  - jemoji